### ISSUE TITLE
In some cases tracking errors

### ISSUE THREAD

**Issue by mixmixmix** [ctorney/uavTracker#20]
Whilst working on my fish's test video:
```
Loading transformations from ../data/salmon//tracks/fishtest10s_MAT.npy
done!
[====                ] 21% 53/250Traceback (most recent call last):
  File "runTracker.py", line 279, in <module>
    main(args)
  File "runTracker.py", line 173, in main
    tracks = tracker.update(np.asarray(detections))
  File "/Users/mix/repos/uavTracker/tracking/yolo_tracker.py", line 269, in update
    dets = np.append(dets,d, axis=0)
  File "/Users/mix/anaconda3/lib/python3.7/site-packages/numpy/lib/function_base.py", line 4528, in append
    return concatenate((arr, values), axis=axis)
ValueError: all the input arrays must have same number of dimensions
```

**Comment by ctorney** [comment]
due to no detections - should be fixed now

**Comment by mixmixmix** [comment]
Thanks! baac069ce11445140d33fabd1858ecf5909155fd
