### ISSUE TITLE
Training on Apple M1 (metal) doesn't really work

### ISSUE THREAD

**Issue by mixmixmix** [ctorney/uavTracker#39]
I can sucesfully run the predictions on M1 mac, with Pipenv setup (https://github.com/ctorney/uavTracker/blob/end-to-end-training/setup/Pipfile)
However, training pretty much explodes. I do not plan actual training on non-linux machines so this is not very important but might be useful to know for some other time

`tensorflow-macos == 2.11.0`, `tensorflow-metal == 0.7.0`

```
(phdeep)  ✘ mix@mixbook  ~/repos/phdeep/uavTracker/train   end-to-end-training ±  python train.py -c ../experiments/alfs22.yml
Opening file../experiments/alfs22.yml
Will train 1 different models for this experiment now
:: Kind notice :: No md5 sum provided. Consider adding it once you have some trained weights / annotated files whatever it is that you are doing to avoid great confusion in the future
Loading all images annotations from ../data/alfs22/annotations//manual_annotated.yml
Fine tuning phase 1. Training top layers.
MD5 check on your file ../data/alfs22//weights/yolo-v3-coco.h5: correct! :D
Metal device set to: Apple M1

systemMemory: 16.00 GB
maxCacheSize: 5.33 GB

Loading weights %s ../data/alfs22//weights/yolo-v3-coco.h5
Loading images from %s ../data/alfs22/annotations/annotations_alf22model_2022Dec28.yml
Reading YaML file finished. Time to lock and load!

Prepared batches now we will compile
COMPILED
Training starts.
  0%|                                                                     | 0/500 [00:00<?, ?epoch/sTraceback (most recent call last):                                     | 0.00/7.00 [00:00<?, ?batch/s]
  File "/Users/mix/repos/phdeep/uavTracker/train/train.py", line 236, in <module>
    main(args)
  File "/Users/mix/repos/phdeep/uavTracker/train/train.py", line 211, in main
    run_full_training(model, config, data_dir, c_date, DEBUG, TEST_RUN)
  File "/Users/mix/repos/phdeep/uavTracker/train/train.py", line 179, in run_full_training
    model.fit(
  File "/Users/mix/.local/share/virtualenvs/phdeep-_TM3t-Se/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/mix/.local/share/virtualenvs/phdeep-_TM3t-Se/lib/python3.10/site-packages/tensorflow/python/eager/execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.NotFoundError: Graph execution error:

Detected at node 'StatefulPartitionedCall' defined at (most recent call last):
    File "/Users/mix/repos/phdeep/uavTracker/train/train.py", line 236, in <module>
      main(args)
    File "/Users/mix/repos/phdeep/uavTracker/train/train.py", line 211, in main
      run_full_training(model, config, data_dir, c_date, DEBUG, TEST_RUN)
    File "/Users/mix/repos/phdeep/uavTracker/train/train.py", line 179, in run_full_training
      model.fit(
    File "/Users/mix/.local/share/virtualenvs/phdeep-_TM3t-Se/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/Users/mix/.local/share/virtualenvs/phdeep-_TM3t-Se/lib/python3.10/site-packages/keras/engine/training.py", line 1650, in fit
      tmp_logs = self.train_function(iterator)
    File "/Users/mix/.local/share/virtualenvs/phdeep-_TM3t-Se/lib/python3.10/site-packages/keras/engine/training.py", line 1249, in train_function
      return step_function(self, iterator)
    File "/Users/mix/.local/share/virtualenvs/phdeep-_TM3t-Se/lib/python3.10/site-packages/keras/engine/training.py", line 1233, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/Users/mix/.local/share/virtualenvs/phdeep-_TM3t-Se/lib/python3.10/site-packages/keras/engine/training.py", line 1222, in run_step
      outputs = model.train_step(data)
    File "/Users/mix/.local/share/virtualenvs/phdeep-_TM3t-Se/lib/python3.10/site-packages/keras/engine/training.py", line 1027, in train_step
      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
    File "/Users/mix/.local/share/virtualenvs/phdeep-_TM3t-Se/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 527, in minimize
      self.apply_gradients(grads_and_vars)
    File "/Users/mix/.local/share/virtualenvs/phdeep-_TM3t-Se/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1140, in apply_gradients
      return super().apply_gradients(grads_and_vars, name=name)
    File "/Users/mix/.local/share/virtualenvs/phdeep-_TM3t-Se/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 634, in apply_gradients
      iteration = self._internal_apply_gradients(grads_and_vars)
    File "/Users/mix/.local/share/virtualenvs/phdeep-_TM3t-Se/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1166, in _internal_apply_gradients
      return tf.__internal__.distribute.interim.maybe_merge_call(
    File "/Users/mix/.local/share/virtualenvs/phdeep-_TM3t-Se/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1216, in _distributed_apply_gradients_fn
      distribution.extended.update(
    File "/Users/mix/.local/share/virtualenvs/phdeep-_TM3t-Se/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 1211, in apply_grad_to_update_var
      return self._update_step_xla(grad, var, id(self._var_key(var)))
Node: 'StatefulPartitionedCall'
could not find registered platform with id: 0x128832dd0
	 [[{{node StatefulPartitionedCall}}]] [Op:__inference_train_function_14634]
  0%|                                                                     | 0/500 [00:07<?, ?epoch/s]
```

**Comment by mixmixmix** [comment]
Using different libraries works:
https://github.com/ctorney/uavTracker/commit/d6e3b4aa14b548cdfcdec15751c6690523aa3556

**Comment by mixmixmix** [comment]
here is a community discussion about this: https://developer.apple.com/forums/thread/721619
