### ISSUE TITLE
How layer names influence model structure

### ISSUE THREAD

**Issue by mixmixmix** [ctorney/uavTracker#45]
I'm hitting some ridiculous problem in TF where somehow layer names were influencing how the model is loaded (even though not loading by name). Not sure if you understand why I cannot have layer called `conv_81 `but can have `conv_special_81` or pretty much any high number? In the model summary the only difference is the name as the order is defined by connections...  https://github.com/ctorney/uavTracker/commit/430c8e74d67fa671850775b35304783784bd385e

**Comment by mixmixmix** [comment]
Here is the error that comes up when I change the name of layer `981` to be `81` (as it follows `80`, so seems logical to me...
```
Traceback (most recent call last):
  File "/Users/mix/repos/phdeep/uavTracker/deepBeastLinker/trainTracker.py", line 165, in <module>
    main(args)
  File "/Users/mix/repos/phdeep/uavTracker/deepBeastLinker/trainTracker.py", line 51, in main
    model = get_train_base(detection_weights, num_class=1)
  File "/Users/mix/repos/phdeep/uavTracker/deepBeastLinker/../models/yolo_models.py", line 304, in get_train_base
    detection_model.load_weights(weights_file, by_name=False)
  File "/Users/mix/.local/share/virtualenvs/phdeep-_TM3t-Se/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/mix/.local/share/virtualenvs/phdeep-_TM3t-Se/lib/python3.10/site-packages/keras/backend.py", line 4360, in _assign_value_to_variable
    variable.assign(value)
ValueError: Cannot assign value to variable ' conv_81/kernel:0': Shape mismatch.The variable shape (1, 1, 1024, 15), and the assigned value shape (27, 1024, 1, 1) are incompatible.
```

**Comment by mixmixmix** [comment]
Here's the model, the only difference is the layer name. I even managed to get a minimal example where all I changed from the working version was a `layer_idx` that is used to create a name and it was breaking....
```
Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to
==================================================================================================
 input_1 (InputLayer)           [(None, None, None,  0           []
                                 3)]

 conv_0 (Conv2D)                (None, None, None,   864         ['input_1[0][0]']
                                32)

 bnorm_0 (BatchNormalization)   (None, None, None,   128         ['conv_0[0][0]']
                                32)

 leaky_0 (LeakyReLU)            (None, None, None,   0           ['bnorm_0[0][0]']
                                32)

 zero_padding2d (ZeroPadding2D)  (None, None, None,   0          ['leaky_0[0][0]']
                                32)

 conv_1 (Conv2D)                (None, None, None,   18432       ['zero_padding2d[0][0]']
                                64)

 bnorm_1 (BatchNormalization)   (None, None, None,   256         ['conv_1[0][0]']
                                64)

 leaky_1 (LeakyReLU)            (None, None, None,   0           ['bnorm_1[0][0]']
                                64)

 conv_2 (Conv2D)                (None, None, None,   2048        ['leaky_1[0][0]']
                                32)

 bnorm_2 (BatchNormalization)   (None, None, None,   128         ['conv_2[0][0]']
                                32)

 leaky_2 (LeakyReLU)            (None, None, None,   0           ['bnorm_2[0][0]']
                                32)

 conv_3 (Conv2D)                (None, None, None,   18432       ['leaky_2[0][0]']
                                64)

 bnorm_3 (BatchNormalization)   (None, None, None,   256         ['conv_3[0][0]']
                                64)

 leaky_3 (LeakyReLU)            (None, None, None,   0           ['bnorm_3[0][0]']
                                64)

 add (Add)                      (None, None, None,   0           ['leaky_1[0][0]',
                                64)                               'leaky_3[0][0]']

 zero_padding2d_1 (ZeroPadding2  (None, None, None,   0          ['add[0][0]']
 D)                             64)

 conv_5 (Conv2D)                (None, None, None,   73728       ['zero_padding2d_1[0][0]']
                                128)

 bnorm_5 (BatchNormalization)   (None, None, None,   512         ['conv_5[0][0]']
                                128)

 leaky_5 (LeakyReLU)            (None, None, None,   0           ['bnorm_5[0][0]']
                                128)

 conv_6 (Conv2D)                (None, None, None,   8192        ['leaky_5[0][0]']
                                64)

 bnorm_6 (BatchNormalization)   (None, None, None,   256         ['conv_6[0][0]']
                                64)

 leaky_6 (LeakyReLU)            (None, None, None,   0           ['bnorm_6[0][0]']
                                64)

 conv_7 (Conv2D)                (None, None, None,   73728       ['leaky_6[0][0]']
                                128)

 bnorm_7 (BatchNormalization)   (None, None, None,   512         ['conv_7[0][0]']
                                128)

 leaky_7 (LeakyReLU)            (None, None, None,   0           ['bnorm_7[0][0]']
                                128)

 add_1 (Add)                    (None, None, None,   0           ['leaky_5[0][0]',
                                128)                              'leaky_7[0][0]']

 conv_9 (Conv2D)                (None, None, None,   8192        ['add_1[0][0]']
                                64)

 bnorm_9 (BatchNormalization)   (None, None, None,   256         ['conv_9[0][0]']
                                64)

 leaky_9 (LeakyReLU)            (None, None, None,   0           ['bnorm_9[0][0]']
                                64)

 conv_10 (Conv2D)               (None, None, None,   73728       ['leaky_9[0][0]']
                                128)

 bnorm_10 (BatchNormalization)  (None, None, None,   512         ['conv_10[0][0]']
                                128)

 leaky_10 (LeakyReLU)           (None, None, None,   0           ['bnorm_10[0][0]']
                                128)

 add_2 (Add)                    (None, None, None,   0           ['add_1[0][0]',
                                128)                              'leaky_10[0][0]']

 zero_padding2d_2 (ZeroPadding2  (None, None, None,   0          ['add_2[0][0]']
 D)                             128)

 conv_12 (Conv2D)               (None, None, None,   294912      ['zero_padding2d_2[0][0]']
                                256)

 bnorm_12 (BatchNormalization)  (None, None, None,   1024        ['conv_12[0][0]']
                                256)

 leaky_12 (LeakyReLU)           (None, None, None,   0           ['bnorm_12[0][0]']
                                256)

 conv_13 (Conv2D)               (None, None, None,   32768       ['leaky_12[0][0]']
                                128)

 bnorm_13 (BatchNormalization)  (None, None, None,   512         ['conv_13[0][0]']
                                128)

 leaky_13 (LeakyReLU)           (None, None, None,   0           ['bnorm_13[0][0]']
                                128)

 conv_14 (Conv2D)               (None, None, None,   294912      ['leaky_13[0][0]']
                                256)

 bnorm_14 (BatchNormalization)  (None, None, None,   1024        ['conv_14[0][0]']
                                256)

 leaky_14 (LeakyReLU)           (None, None, None,   0           ['bnorm_14[0][0]']
                                256)

 add_3 (Add)                    (None, None, None,   0           ['leaky_12[0][0]',
                                256)                              'leaky_14[0][0]']

 conv_16 (Conv2D)               (None, None, None,   32768       ['add_3[0][0]']
                                128)

 bnorm_16 (BatchNormalization)  (None, None, None,   512         ['conv_16[0][0]']
                                128)

 leaky_16 (LeakyReLU)           (None, None, None,   0           ['bnorm_16[0][0]']
                                128)

 conv_17 (Conv2D)               (None, None, None,   294912      ['leaky_16[0][0]']
                                256)

 bnorm_17 (BatchNormalization)  (None, None, None,   1024        ['conv_17[0][0]']
                                256)

 leaky_17 (LeakyReLU)           (None, None, None,   0           ['bnorm_17[0][0]']
                                256)

 add_4 (Add)                    (None, None, None,   0           ['add_3[0][0]',
                                256)                              'leaky_17[0][0]']

 conv_19 (Conv2D)               (None, None, None,   32768       ['add_4[0][0]']
                                128)

 bnorm_19 (BatchNormalization)  (None, None, None,   512         ['conv_19[0][0]']
                                128)

 leaky_19 (LeakyReLU)           (None, None, None,   0           ['bnorm_19[0][0]']
                                128)

 conv_20 (Conv2D)               (None, None, None,   294912      ['leaky_19[0][0]']
                                256)

 bnorm_20 (BatchNormalization)  (None, None, None,   1024        ['conv_20[0][0]']
                                256)

 leaky_20 (LeakyReLU)           (None, None, None,   0           ['bnorm_20[0][0]']
                                256)

 add_5 (Add)                    (None, None, None,   0           ['add_4[0][0]',
                                256)                              'leaky_20[0][0]']

 conv_22 (Conv2D)               (None, None, None,   32768       ['add_5[0][0]']
                                128)

 bnorm_22 (BatchNormalization)  (None, None, None,   512         ['conv_22[0][0]']
                                128)

 leaky_22 (LeakyReLU)           (None, None, None,   0           ['bnorm_22[0][0]']
                                128)

 conv_23 (Conv2D)               (None, None, None,   294912      ['leaky_22[0][0]']
                                256)

 bnorm_23 (BatchNormalization)  (None, None, None,   1024        ['conv_23[0][0]']
                                256)

 leaky_23 (LeakyReLU)           (None, None, None,   0           ['bnorm_23[0][0]']
                                256)

 add_6 (Add)                    (None, None, None,   0           ['add_5[0][0]',
                                256)                              'leaky_23[0][0]']

 conv_25 (Conv2D)               (None, None, None,   32768       ['add_6[0][0]']
                                128)

 bnorm_25 (BatchNormalization)  (None, None, None,   512         ['conv_25[0][0]']
                                128)

 leaky_25 (LeakyReLU)           (None, None, None,   0           ['bnorm_25[0][0]']
                                128)

 conv_26 (Conv2D)               (None, None, None,   294912      ['leaky_25[0][0]']
                                256)

 bnorm_26 (BatchNormalization)  (None, None, None,   1024        ['conv_26[0][0]']
                                256)

 leaky_26 (LeakyReLU)           (None, None, None,   0           ['bnorm_26[0][0]']
                                256)

 add_7 (Add)                    (None, None, None,   0           ['add_6[0][0]',
                                256)                              'leaky_26[0][0]']

 conv_28 (Conv2D)               (None, None, None,   32768       ['add_7[0][0]']
                                128)

 bnorm_28 (BatchNormalization)  (None, None, None,   512         ['conv_28[0][0]']
                                128)

 leaky_28 (LeakyReLU)           (None, None, None,   0           ['bnorm_28[0][0]']
                                128)

 conv_29 (Conv2D)               (None, None, None,   294912      ['leaky_28[0][0]']
                                256)

 bnorm_29 (BatchNormalization)  (None, None, None,   1024        ['conv_29[0][0]']
                                256)

 leaky_29 (LeakyReLU)           (None, None, None,   0           ['bnorm_29[0][0]']
                                256)

 add_8 (Add)                    (None, None, None,   0           ['add_7[0][0]',
                                256)                              'leaky_29[0][0]']

 conv_31 (Conv2D)               (None, None, None,   32768       ['add_8[0][0]']
                                128)

 bnorm_31 (BatchNormalization)  (None, None, None,   512         ['conv_31[0][0]']
                                128)

 leaky_31 (LeakyReLU)           (None, None, None,   0           ['bnorm_31[0][0]']
                                128)

 conv_32 (Conv2D)               (None, None, None,   294912      ['leaky_31[0][0]']
                                256)

 bnorm_32 (BatchNormalization)  (None, None, None,   1024        ['conv_32[0][0]']
                                256)

 leaky_32 (LeakyReLU)           (None, None, None,   0           ['bnorm_32[0][0]']
                                256)

 add_9 (Add)                    (None, None, None,   0           ['add_8[0][0]',
                                256)                              'leaky_32[0][0]']

 conv_34 (Conv2D)               (None, None, None,   32768       ['add_9[0][0]']
                                128)

 bnorm_34 (BatchNormalization)  (None, None, None,   512         ['conv_34[0][0]']
                                128)

 leaky_34 (LeakyReLU)           (None, None, None,   0           ['bnorm_34[0][0]']
                                128)

 conv_35 (Conv2D)               (None, None, None,   294912      ['leaky_34[0][0]']
                                256)

 bnorm_35 (BatchNormalization)  (None, None, None,   1024        ['conv_35[0][0]']
                                256)

 leaky_35 (LeakyReLU)           (None, None, None,   0           ['bnorm_35[0][0]']
                                256)

 add_10 (Add)                   (None, None, None,   0           ['add_9[0][0]',
                                256)                              'leaky_35[0][0]']

 zero_padding2d_3 (ZeroPadding2  (None, None, None,   0          ['add_10[0][0]']
 D)                             256)

 conv_37 (Conv2D)               (None, None, None,   1179648     ['zero_padding2d_3[0][0]']
                                512)

 bnorm_37 (BatchNormalization)  (None, None, None,   2048        ['conv_37[0][0]']
                                512)

 leaky_37 (LeakyReLU)           (None, None, None,   0           ['bnorm_37[0][0]']
                                512)

 conv_38 (Conv2D)               (None, None, None,   131072      ['leaky_37[0][0]']
                                256)

 bnorm_38 (BatchNormalization)  (None, None, None,   1024        ['conv_38[0][0]']
                                256)

 leaky_38 (LeakyReLU)           (None, None, None,   0           ['bnorm_38[0][0]']
                                256)

 conv_39 (Conv2D)               (None, None, None,   1179648     ['leaky_38[0][0]']
                                512)

 bnorm_39 (BatchNormalization)  (None, None, None,   2048        ['conv_39[0][0]']
                                512)

 leaky_39 (LeakyReLU)           (None, None, None,   0           ['bnorm_39[0][0]']
                                512)

 add_11 (Add)                   (None, None, None,   0           ['leaky_37[0][0]',
                                512)                              'leaky_39[0][0]']

 conv_41 (Conv2D)               (None, None, None,   131072      ['add_11[0][0]']
                                256)

 bnorm_41 (BatchNormalization)  (None, None, None,   1024        ['conv_41[0][0]']
                                256)

 leaky_41 (LeakyReLU)           (None, None, None,   0           ['bnorm_41[0][0]']
                                256)

 conv_42 (Conv2D)               (None, None, None,   1179648     ['leaky_41[0][0]']
                                512)

 bnorm_42 (BatchNormalization)  (None, None, None,   2048        ['conv_42[0][0]']
                                512)

 leaky_42 (LeakyReLU)           (None, None, None,   0           ['bnorm_42[0][0]']
                                512)

 add_12 (Add)                   (None, None, None,   0           ['add_11[0][0]',
                                512)                              'leaky_42[0][0]']

 conv_44 (Conv2D)               (None, None, None,   131072      ['add_12[0][0]']
                                256)

 bnorm_44 (BatchNormalization)  (None, None, None,   1024        ['conv_44[0][0]']
                                256)

 leaky_44 (LeakyReLU)           (None, None, None,   0           ['bnorm_44[0][0]']
                                256)

 conv_45 (Conv2D)               (None, None, None,   1179648     ['leaky_44[0][0]']
                                512)

 bnorm_45 (BatchNormalization)  (None, None, None,   2048        ['conv_45[0][0]']
                                512)

 leaky_45 (LeakyReLU)           (None, None, None,   0           ['bnorm_45[0][0]']
                                512)

 add_13 (Add)                   (None, None, None,   0           ['add_12[0][0]',
                                512)                              'leaky_45[0][0]']

 conv_47 (Conv2D)               (None, None, None,   131072      ['add_13[0][0]']
                                256)

 bnorm_47 (BatchNormalization)  (None, None, None,   1024        ['conv_47[0][0]']
                                256)

 leaky_47 (LeakyReLU)           (None, None, None,   0           ['bnorm_47[0][0]']
                                256)

 conv_48 (Conv2D)               (None, None, None,   1179648     ['leaky_47[0][0]']
                                512)

 bnorm_48 (BatchNormalization)  (None, None, None,   2048        ['conv_48[0][0]']
                                512)

 leaky_48 (LeakyReLU)           (None, None, None,   0           ['bnorm_48[0][0]']
                                512)

 add_14 (Add)                   (None, None, None,   0           ['add_13[0][0]',
                                512)                              'leaky_48[0][0]']

 conv_50 (Conv2D)               (None, None, None,   131072      ['add_14[0][0]']
                                256)

 bnorm_50 (BatchNormalization)  (None, None, None,   1024        ['conv_50[0][0]']
                                256)

 leaky_50 (LeakyReLU)           (None, None, None,   0           ['bnorm_50[0][0]']
                                256)

 conv_51 (Conv2D)               (None, None, None,   1179648     ['leaky_50[0][0]']
                                512)

 bnorm_51 (BatchNormalization)  (None, None, None,   2048        ['conv_51[0][0]']
                                512)

 leaky_51 (LeakyReLU)           (None, None, None,   0           ['bnorm_51[0][0]']
                                512)

 add_15 (Add)                   (None, None, None,   0           ['add_14[0][0]',
                                512)                              'leaky_51[0][0]']

 conv_53 (Conv2D)               (None, None, None,   131072      ['add_15[0][0]']
                                256)

 bnorm_53 (BatchNormalization)  (None, None, None,   1024        ['conv_53[0][0]']
                                256)

 leaky_53 (LeakyReLU)           (None, None, None,   0           ['bnorm_53[0][0]']
                                256)

 conv_54 (Conv2D)               (None, None, None,   1179648     ['leaky_53[0][0]']
                                512)

 bnorm_54 (BatchNormalization)  (None, None, None,   2048        ['conv_54[0][0]']
                                512)

 leaky_54 (LeakyReLU)           (None, None, None,   0           ['bnorm_54[0][0]']
                                512)

 add_16 (Add)                   (None, None, None,   0           ['add_15[0][0]',
                                512)                              'leaky_54[0][0]']

 conv_56 (Conv2D)               (None, None, None,   131072      ['add_16[0][0]']
                                256)

 bnorm_56 (BatchNormalization)  (None, None, None,   1024        ['conv_56[0][0]']
                                256)

 leaky_56 (LeakyReLU)           (None, None, None,   0           ['bnorm_56[0][0]']
                                256)

 conv_57 (Conv2D)               (None, None, None,   1179648     ['leaky_56[0][0]']
                                512)

 bnorm_57 (BatchNormalization)  (None, None, None,   2048        ['conv_57[0][0]']
                                512)

 leaky_57 (LeakyReLU)           (None, None, None,   0           ['bnorm_57[0][0]']
                                512)

 add_17 (Add)                   (None, None, None,   0           ['add_16[0][0]',
                                512)                              'leaky_57[0][0]']

 conv_59 (Conv2D)               (None, None, None,   131072      ['add_17[0][0]']
                                256)

 bnorm_59 (BatchNormalization)  (None, None, None,   1024        ['conv_59[0][0]']
                                256)

 leaky_59 (LeakyReLU)           (None, None, None,   0           ['bnorm_59[0][0]']
                                256)

 conv_60 (Conv2D)               (None, None, None,   1179648     ['leaky_59[0][0]']
                                512)

 bnorm_60 (BatchNormalization)  (None, None, None,   2048        ['conv_60[0][0]']
                                512)

 leaky_60 (LeakyReLU)           (None, None, None,   0           ['bnorm_60[0][0]']
                                512)

 add_18 (Add)                   (None, None, None,   0           ['add_17[0][0]',
                                512)                              'leaky_60[0][0]']

 zero_padding2d_4 (ZeroPadding2  (None, None, None,   0          ['add_18[0][0]']
 D)                             512)

 conv_62 (Conv2D)               (None, None, None,   4718592     ['zero_padding2d_4[0][0]']
                                1024)

 bnorm_62 (BatchNormalization)  (None, None, None,   4096        ['conv_62[0][0]']
                                1024)

 leaky_62 (LeakyReLU)           (None, None, None,   0           ['bnorm_62[0][0]']
                                1024)

 conv_63 (Conv2D)               (None, None, None,   524288      ['leaky_62[0][0]']
                                512)

 bnorm_63 (BatchNormalization)  (None, None, None,   2048        ['conv_63[0][0]']
                                512)

 leaky_63 (LeakyReLU)           (None, None, None,   0           ['bnorm_63[0][0]']
                                512)

 conv_64 (Conv2D)               (None, None, None,   4718592     ['leaky_63[0][0]']
                                1024)

 bnorm_64 (BatchNormalization)  (None, None, None,   4096        ['conv_64[0][0]']
                                1024)

 leaky_64 (LeakyReLU)           (None, None, None,   0           ['bnorm_64[0][0]']
                                1024)

 add_19 (Add)                   (None, None, None,   0           ['leaky_62[0][0]',
                                1024)                             'leaky_64[0][0]']

 conv_66 (Conv2D)               (None, None, None,   524288      ['add_19[0][0]']
                                512)

 bnorm_66 (BatchNormalization)  (None, None, None,   2048        ['conv_66[0][0]']
                                512)

 leaky_66 (LeakyReLU)           (None, None, None,   0           ['bnorm_66[0][0]']
                                512)

 conv_67 (Conv2D)               (None, None, None,   4718592     ['leaky_66[0][0]']
                                1024)

 bnorm_67 (BatchNormalization)  (None, None, None,   4096        ['conv_67[0][0]']
                                1024)

 leaky_67 (LeakyReLU)           (None, None, None,   0           ['bnorm_67[0][0]']
                                1024)

 add_20 (Add)                   (None, None, None,   0           ['add_19[0][0]',
                                1024)                             'leaky_67[0][0]']

 conv_69 (Conv2D)               (None, None, None,   524288      ['add_20[0][0]']
                                512)

 bnorm_69 (BatchNormalization)  (None, None, None,   2048        ['conv_69[0][0]']
                                512)

 leaky_69 (LeakyReLU)           (None, None, None,   0           ['bnorm_69[0][0]']
                                512)

 conv_70 (Conv2D)               (None, None, None,   4718592     ['leaky_69[0][0]']
                                1024)

 bnorm_70 (BatchNormalization)  (None, None, None,   4096        ['conv_70[0][0]']
                                1024)

 leaky_70 (LeakyReLU)           (None, None, None,   0           ['bnorm_70[0][0]']
                                1024)

 add_21 (Add)                   (None, None, None,   0           ['add_20[0][0]',
                                1024)                             'leaky_70[0][0]']

 conv_72 (Conv2D)               (None, None, None,   524288      ['add_21[0][0]']
                                512)

 bnorm_72 (BatchNormalization)  (None, None, None,   2048        ['conv_72[0][0]']
                                512)

 leaky_72 (LeakyReLU)           (None, None, None,   0           ['bnorm_72[0][0]']
                                512)

 conv_73 (Conv2D)               (None, None, None,   4718592     ['leaky_72[0][0]']
                                1024)

 bnorm_73 (BatchNormalization)  (None, None, None,   4096        ['conv_73[0][0]']
                                1024)

 leaky_73 (LeakyReLU)           (None, None, None,   0           ['bnorm_73[0][0]']
                                1024)

 add_22 (Add)                   (None, None, None,   0           ['add_21[0][0]',
                                1024)                             'leaky_73[0][0]']

 conv_75 (Conv2D)               (None, None, None,   524288      ['add_22[0][0]']
                                512)

 bnorm_75 (BatchNormalization)  (None, None, None,   2048        ['conv_75[0][0]']
                                512)

 leaky_75 (LeakyReLU)           (None, None, None,   0           ['bnorm_75[0][0]']
                                512)

 conv_76 (Conv2D)               (None, None, None,   4718592     ['leaky_75[0][0]']
                                1024)

 bnorm_76 (BatchNormalization)  (None, None, None,   4096        ['conv_76[0][0]']
                                1024)

 leaky_76 (LeakyReLU)           (None, None, None,   0           ['bnorm_76[0][0]']
                                1024)

 conv_77 (Conv2D)               (None, None, None,   524288      ['leaky_76[0][0]']
                                512)

 bnorm_77 (BatchNormalization)  (None, None, None,   2048        ['conv_77[0][0]']
                                512)

 leaky_77 (LeakyReLU)           (None, None, None,   0           ['bnorm_77[0][0]']
                                512)

 conv_78 (Conv2D)               (None, None, None,   4718592     ['leaky_77[0][0]']
                                1024)

 bnorm_78 (BatchNormalization)  (None, None, None,   4096        ['conv_78[0][0]']
                                1024)

 leaky_78 (LeakyReLU)           (None, None, None,   0           ['bnorm_78[0][0]']
                                1024)

 conv_79 (Conv2D)               (None, None, None,   524288      ['leaky_78[0][0]']
                                512)

 bnorm_79 (BatchNormalization)  (None, None, None,   2048        ['conv_79[0][0]']
                                512)

 leaky_79 (LeakyReLU)           (None, None, None,   0           ['bnorm_79[0][0]']
                                512)

 conv_84 (Conv2D)               (None, None, None,   131072      ['leaky_79[0][0]']
                                256)

 bnorm_84 (BatchNormalization)  (None, None, None,   1024        ['conv_84[0][0]']
                                256)

 leaky_84 (LeakyReLU)           (None, None, None,   0           ['bnorm_84[0][0]']
                                256)

 up_sampling2d (UpSampling2D)   (None, None, None,   0           ['leaky_84[0][0]']
                                256)

 concatenate (Concatenate)      (None, None, None,   0           ['up_sampling2d[0][0]',
                                768)                              'add_18[0][0]']

 conv_87 (Conv2D)               (None, None, None,   196608      ['concatenate[0][0]']
                                256)

 bnorm_87 (BatchNormalization)  (None, None, None,   1024        ['conv_87[0][0]']
                                256)

 leaky_87 (LeakyReLU)           (None, None, None,   0           ['bnorm_87[0][0]']
                                256)

 conv_88 (Conv2D)               (None, None, None,   1179648     ['leaky_87[0][0]']
                                512)

 bnorm_88 (BatchNormalization)  (None, None, None,   2048        ['conv_88[0][0]']
                                512)

 leaky_88 (LeakyReLU)           (None, None, None,   0           ['bnorm_88[0][0]']
                                512)

 conv_89 (Conv2D)               (None, None, None,   131072      ['leaky_88[0][0]']
                                256)

 bnorm_89 (BatchNormalization)  (None, None, None,   1024        ['conv_89[0][0]']
                                256)

 leaky_89 (LeakyReLU)           (None, None, None,   0           ['bnorm_89[0][0]']
                                256)

 conv_90 (Conv2D)               (None, None, None,   1179648     ['leaky_89[0][0]']
                                512)

 bnorm_90 (BatchNormalization)  (None, None, None,   2048        ['conv_90[0][0]']
                                512)

 leaky_90 (LeakyReLU)           (None, None, None,   0           ['bnorm_90[0][0]']
                                512)

 conv_91 (Conv2D)               (None, None, None,   131072      ['leaky_90[0][0]']
                                256)

 bnorm_91 (BatchNormalization)  (None, None, None,   1024        ['conv_91[0][0]']
                                256)

 leaky_91 (LeakyReLU)           (None, None, None,   0           ['bnorm_91[0][0]']
                                256)

 conv_96 (Conv2D)               (None, None, None,   32768       ['leaky_91[0][0]']
                                128)

 bnorm_96 (BatchNormalization)  (None, None, None,   512         ['conv_96[0][0]']
                                128)

 leaky_96 (LeakyReLU)           (None, None, None,   0           ['bnorm_96[0][0]']
                                128)

 up_sampling2d_1 (UpSampling2D)  (None, None, None,   0          ['leaky_96[0][0]']
                                128)

 concatenate_1 (Concatenate)    (None, None, None,   0           ['up_sampling2d_1[0][0]',
                                384)                              'add_10[0][0]']

 conv_99 (Conv2D)               (None, None, None,   49152       ['concatenate_1[0][0]']
                                128)

 bnorm_99 (BatchNormalization)  (None, None, None,   512         ['conv_99[0][0]']
                                128)

 leaky_99 (LeakyReLU)           (None, None, None,   0           ['bnorm_99[0][0]']
                                128)

 conv_100 (Conv2D)              (None, None, None,   294912      ['leaky_99[0][0]']
                                256)

 bnorm_100 (BatchNormalization)  (None, None, None,   1024       ['conv_100[0][0]']
                                256)

 leaky_100 (LeakyReLU)          (None, None, None,   0           ['bnorm_100[0][0]']
                                256)

 conv_101 (Conv2D)              (None, None, None,   32768       ['leaky_100[0][0]']
                                128)

 bnorm_101 (BatchNormalization)  (None, None, None,   512        ['conv_101[0][0]']
                                128)

 leaky_101 (LeakyReLU)          (None, None, None,   0           ['bnorm_101[0][0]']
                                128)

 conv_102 (Conv2D)              (None, None, None,   294912      ['leaky_101[0][0]']
                                256)

 bnorm_102 (BatchNormalization)  (None, None, None,   1024       ['conv_102[0][0]']
                                256)

 leaky_102 (LeakyReLU)          (None, None, None,   0           ['bnorm_102[0][0]']
                                256)

 conv_103 (Conv2D)              (None, None, None,   32768       ['leaky_102[0][0]']
                                128)

 bnorm_103 (BatchNormalization)  (None, None, None,   512        ['conv_103[0][0]']
                                128)

 leaky_103 (LeakyReLU)          (None, None, None,   0           ['bnorm_103[0][0]']
                                128)

 conv_80 (Conv2D)               (None, None, None,   4718592     ['leaky_79[0][0]']
                                1024)

 conv_92 (Conv2D)               (None, None, None,   1179648     ['leaky_91[0][0]']
                                512)

 conv_104 (Conv2D)              (None, None, None,   294912      ['leaky_103[0][0]']
                                256)

 bnorm_80 (BatchNormalization)  (None, None, None,   4096        ['conv_80[0][0]']
                                1024)

 bnorm_92 (BatchNormalization)  (None, None, None,   2048        ['conv_92[0][0]']
                                512)

 bnorm_104 (BatchNormalization)  (None, None, None,   1024       ['conv_104[0][0]']
                                256)

 leaky_80 (LeakyReLU)           (None, None, None,   0           ['bnorm_80[0][0]']
                                1024)

 leaky_92 (LeakyReLU)           (None, None, None,   0           ['bnorm_92[0][0]']
                                512)

 leaky_104 (LeakyReLU)          (None, None, None,   0           ['bnorm_104[0][0]']
                                256)

 conv_81 (Conv2D)               (None, None, None,   15375       ['leaky_80[0][0]']
                                15)

 conv_93 (Conv2D)               (None, None, None,   7695        ['leaky_92[0][0]']
                                15)

 conv_106 (Conv2D)              (None, None, None,   3855        ['leaky_104[0][0]']
                                15)

 lambda (Lambda)                (None, None, None,   0           ['conv_81[0][0]']
                                3, 5)

 lambda_8 (Lambda)              (None, None, None,   0           ['conv_93[0][0]']
                                3, 5)

 lambda_16 (Lambda)             (None, None, None,   0           ['conv_106[0][0]']
                                3, 5)

 lambda_2 (Lambda)              (None, None, None,   0           ['lambda[0][0]']
                                3, 2)

 lambda_10 (Lambda)             (None, None, None,   0           ['lambda_8[0][0]']
                                3, 2)

 lambda_18 (Lambda)             (None, None, None,   0           ['lambda_16[0][0]']
                                3, 2)

 activation (Activation)        (None, None, None,   0           ['lambda_2[0][0]']
                                3, 2)

 lambda_4 (Lambda)              (None, None, None,   0           ['lambda[0][0]']
                                3, 2)

 lambda_6 (Lambda)              (None, None, None,   0           ['lambda[0][0]']
                                3, 0)

 lambda_7 (Lambda)              (None, None, None,   0           ['lambda[0][0]']
                                3, 3)

 activation_4 (Activation)      (None, None, None,   0           ['lambda_10[0][0]']
                                3, 2)

 lambda_12 (Lambda)             (None, None, None,   0           ['lambda_8[0][0]']
                                3, 2)

 lambda_14 (Lambda)             (None, None, None,   0           ['lambda_8[0][0]']
                                3, 0)

 lambda_15 (Lambda)             (None, None, None,   0           ['lambda_8[0][0]']
                                3, 3)

 activation_8 (Activation)      (None, None, None,   0           ['lambda_18[0][0]']
                                3, 2)

 lambda_20 (Lambda)             (None, None, None,   0           ['lambda_16[0][0]']
                                3, 2)

 lambda_22 (Lambda)             (None, None, None,   0           ['lambda_16[0][0]']
                                3, 0)

 lambda_23 (Lambda)             (None, None, None,   0           ['lambda_16[0][0]']
                                3, 3)

 lambda_3 (Lambda)              (None, None, None,   0           ['activation[0][0]',
                                3, 2)                             'input_1[0][0]']

 lambda_5 (Lambda)              (None, None, None,   0           ['lambda_4[0][0]']
                                3, 2)

 activation_1 (Activation)      (None, None, None,   0           ['lambda_6[0][0]']
                                3, 0)

 activation_2 (Activation)      (None, None, None,   0           ['lambda_7[0][0]']
                                3, 3)

 lambda_11 (Lambda)             (None, None, None,   0           ['activation_4[0][0]',
                                3, 2)                             'input_1[0][0]']

 lambda_13 (Lambda)             (None, None, None,   0           ['lambda_12[0][0]']
                                3, 2)

 activation_5 (Activation)      (None, None, None,   0           ['lambda_14[0][0]']
                                3, 0)

 activation_6 (Activation)      (None, None, None,   0           ['lambda_15[0][0]']
                                3, 3)

 lambda_19 (Lambda)             (None, None, None,   0           ['activation_8[0][0]',
                                3, 2)                             'input_1[0][0]']

 lambda_21 (Lambda)             (None, None, None,   0           ['lambda_20[0][0]']
                                3, 2)

 activation_9 (Activation)      (None, None, None,   0           ['lambda_22[0][0]']
                                3, 0)

 activation_10 (Activation)     (None, None, None,   0           ['lambda_23[0][0]']
                                3, 3)

 concatenate_2 (Concatenate)    (None, None, None,   0           ['lambda_3[0][0]',
                                3, 7)                             'lambda_5[0][0]',
                                                                  'activation_1[0][0]',
                                                                  'activation_2[0][0]']

 concatenate_3 (Concatenate)    (None, None, None,   0           ['lambda_11[0][0]',
                                3, 7)                             'lambda_13[0][0]',
                                                                  'activation_5[0][0]',
                                                                  'activation_6[0][0]']

 concatenate_4 (Concatenate)    (None, None, None,   0           ['lambda_19[0][0]',
                                3, 7)                             'lambda_21[0][0]',
                                                                  'activation_9[0][0]',
                                                                  'activation_10[0][0]']

==================================================================================================
Total params: 61,570,957
Trainable params: 0
Non-trainable params: 61,570,957
__________________________________________________________________________________________________
None
```

**Comment by mixmixmix** [comment]
just occurred to me that maybe those layers have to be loaded by_name as we only use part of the model.... Will test later

**Comment by mixmixmix** [comment]
Still some problems down the line but the model loads weights. Indeed this is where they are loaded by name as not the whole detection model is loaded... https://github.com/ctorney/uavTracker/commit/9deb0411e22e5df7dbf0d76b28385bd7835bf0a9
